tags:
  - Trainers
summary: "Отримати список всіх тренерів"
description: "Повертає список тренерів фітнес-клубу"
responses:
  200:
    description: "Список тренерів"
    schema:
      type: array
      items:
        type: object
        properties:
          trainer_id:
            type: integer
            example: 1
          name:
            type: string
            example: "Vitalii"
          surname:
            type: string
            example: "Savchuk"
          phone_number:
            type: string
            example: "123-456-7890"
